enum USE_PAGINATION_ACTION_TYPE {
    LOWEST_PAGE = 'LOWEST_PAGE',
    HIGHEST_PAGE = 'HIGHEST_PAGE',
    PAGE = 'PAGE',
    PER_PAGE = 'PER_PAGE',
    FILTER = 'FILTER',
    SORT = 'SORT',
    RESET = 'RESET',
    TOTAL_PAGE = 'TOTAL_PAGE'
}

export default USE_PAGINATION_ACTION_TYPE